# Generated by Django 3.1 on 2021-09-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_auto_20210901_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookspurch',
            name='BookImg',
            field=models.ImageField(default='images\\default.png', upload_to='images'),
        ),
    ]
