# Generated by Django 3.1 on 2021-09-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_bookspurch_bookimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Items', models.IntegerField(null=True)),
                ('Name', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
