# Generated by Django 3.1 on 2021-09-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
