# Generated by Django 3.1 on 2021-09-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0002_auto_20210901_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerbooks',
            name='BookImg',
            field=models.ImageField(default='images\\default.png', upload_to='images'),
        ),
    ]
