# Generated by Django 3.1 on 2021-09-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_sellerbooks_bookimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerbooks',
            name='Items',
            field=models.IntegerField(null=True),
        ),
    ]
