# Generated by Django 3.1 on 2021-09-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0004_sellerbooks_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerbooks',
            name='BuyerAddr',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sellerbooks',
            name='Mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
