# Generated by Django 3.1 on 2021-09-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0005_auto_20210903_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerbooks',
            name='unique',
            field=models.BooleanField(default=False),
        ),
    ]
